import type {Metadata} from "next";
import "./globals.css";
import {Inter} from "next/font/google";
import {HeaderComponent} from "@/components/header";
import {FooterComponent} from "@/components/footer";
import {ModalProvider} from "@/context/ModalContext";

const inter = Inter({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} antialiased`}>
				<ModalProvider>
					<HeaderComponent />
					{children}
					<FooterComponent />
				</ModalProvider>
			</body>
		</html>
	);
}
